###

POST http://127.0.0.1:8000/connections/appstore
Accept: application/json
Content-Type: application/json

{
  "region": "us",
  "slug": "spotify-music-and-podcasts",
  "appid": "id324684580",
  "description": "Spotify Appstore application"
}


####